INSERT INTO `job_analytics`.`skills`
(`skill`,
`group`)
VALUES
('Scala',null),
('Delphi',null),
('Visual Basic',null),
('R',null),
('ASP',null),
('Perl',null),
('SQL',null),
('Assembly',null),
('C#',null),
('Objective ',null),
('Ruby',null),
('Shell',null),
('Python',null),
('C++',null),
('JavaScript',null),
('PHP',null),
('Java',null),
('HTML',null),
('HTML5',null),
('CSS',null),
('XML',null),
('rest',null),
('restfull',null),
('SOAP',null),
('Swing','Java'),
('Maven','Java'),
('Ant','Java'),
('spring','Java'),
('jsf','Java'),
('struts','Java'),
('gwt','Java'),
('play','Java'),
('wicket','Java'),
('grails','Java'),
('vaadin','Java'),
('cloud',null),
('aws','cloud'),
('android','OS'),
('iOS','OS'),
('Linux','OS'),
('Unix','OS'),
('BSD','OS'),
('Windows',null),
('Eclipse','IDE'),
('IntelliJ','IDE'),
('Git','version control'),
('SVN','version control'),
('Mercurial','version control'),
('Subversion','version control'),
('CVS','version control'),
('NumPy','python'),
('Pandas','python'),
('SciPy','python'),
('Mechanize','python'),
('Pyramid','python'),
('Bottle','python'),
('Django','python'),
('Flask','python'),
('Multithreading',null),
('Multiprocessing',null),
('Concurrency',null),
('Math',null),
('Statistics',null),
('Zookeeper',null),
('tcp',null),
('ftp',null),
('http',null),
('MySQL','SQL'),
('Oracle','SQL'),
('Postgre','SQL'),
('Sybase','SQL'),
('RDBMS','SQL'),
('Hadoop','NoSql'),
('HDFS','NoSql'),
('Cassandra','NoSql'),
('MongoDB','NoSql'),
('Elasticsearch','NoSql'),
('Redis','NoSql'),
('Pig','NoSql'),
('Hive','NoSql'),
('C',null);